image: gradle:7.6-jdk17-focal

stages:
  - build
  - afterBuild

variables:
  GRADLE_OPTS: >
    -Dorg.gradle.daemon=false

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

include:
  - project: 'mr_drednote/gitlab-ci/v1'
    file:
      - 'stages/build.yml'
      - 'stages/versioning.yml'
      - 'stages/badges.yml'
