package com.github.drednote.telegram.core;

public enum RequestType {
  MESSAGE,
  COMMAND,
  INLINE_QUERY,
  CHOSEN_INLINE_QUERY,
  CALLBACK_QUERY,
  SHIPPING_QUERY,
  PRE_CHECKOUT_QUERY,
  POLL,
  POLL_ANSWER,
  CHAT_MEMBER_UPDATED,
  CHAT_JOIN_REQUEST
}
