spring:
  main:
    web-application-type: servlet
  application:
    name: assistant-bot
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_starter
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      connection-timeout: 30000
      minimum-idle: 3

drednote:
  telegram:
    token: ${BOT_TOKEN}
    # scenario configuration
    scenario.values.telegram-settings:
      type: Response_message_processing
      request:
        patterns: [ /test ]
        requestTypes: [ MESSAGE ]
        messageTypes: [ COMMAND ]
      action-references:
        - "io.github.drednote.examples.scenario.ScenarioFactory#initialTest(ActionContext)"
      #source: will be automatically put because of this source is Initial
      target: TEST
      graph:
        - id: choose
          children:
            - id: print
      steps:
        choose:
          type: Rollback
          request:
            patterns: [ "choose-{value:.*}" ]
            requestTypes: [ CALLBACK_QUERY ]
          action-references:
            - "ScenarioFactory#choose"
          source: TEST
          target: GET
          rollback:
            action-references:
              - "scenarioBack"
            request:
              patterns: [ back ]
              requestTypes: [ CALLBACK_QUERY ]
        print:
          type: external
          request:
            patterns: [ print ]
            requestTypes: [ CALLBACK_QUERY ]
          action-references:
            - "ScenarioFactory#print"
          source: GET
          target: GET