package io.github.drednote.examples.scenario;

public enum State {
    SCENARIO_1_START,
    SCENARIO_1_SHOW_MENU,
    SCENARIO_1_SHOW_WEATHER,
    SCENARIO_1_CHANGE_PASSWORD,
    SCENARIO_1_AWAIT_NEW_PASSWORD,
    SCENARIO_1_PASS_WAS_CHANGED,
    SCENARIO_1_CHANGE_PASSWORD_NO_POSSIBLE,

    SCENARIO_1_GLOBAL_ERROR,
    SCENARIO_1_LOCAL1_ERROR,
    SCENARIO_1_LOCAL2_ERROR,
    SCENARIO_FUTURE_ERROR,
    SCENARIO_1_EXIT,
}
