name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

#      - name: Archive build artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: build-artifacts
#          path: build/libs/*.jar