name: Publish to Maven Central
on:
  create:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag name
        run: echo "Tag name is ${GITHUB_REF#refs/tags/}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Restore build artifacts cache
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Publish to Maven Central
        run: |
          # Ваши шаги для публикации в Maven Central