name: Release to Maven Central
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ vars.JAVA_VERSION }}
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew --build-cache build

      - name: Get version
        id: version
        run: echo "tag_version=$(echo ${GITHUB_REF#refs/tags/} | cut -c 2-)" >> $GITHUB_OUTPUT

      - name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.GNUPG_SECRET_KEY }}") | gpg --batch --import

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GRADLE_VARS: |
            -Psigning.gnupg.keyName=${{ secrets.GNUPG_KEY_ID }}
            -Psigning.gnupg.passphrase=${{ secrets.GNUPG_PASSPHRASE }}
            -Ptag_version=${{ steps.version.outputs.tag_version }}
        run: ./gradlew ${GRADLE_VARS} publish --no-daemon
