name: Release to Maven Central
on:
  push:
    tags:
      - 'v*'


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get version
        id: version
        run: echo "tag_version=$(echo ${GITHUB_REF#refs/tags/} | cut -c 2-)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ vars.JAVA_VERSION }}
      - name: Build with Gradle
        run: ./gradlew --build-cache build
      - name: Publish to Maven Central
        env:
          GRADLE_VARS: >
            -Psigning.gnupg.keyName=${{ secrets.GNUPG_KEY_ID }}
            -Psigning.gnupg.passphrase=${{ secrets.GNUPG_PASSPHRASE }}
            -POSSRH_USERNAME=${{ secrets.OSSRH_USERNAME }}
            -POSSRH_PASSWORD=${{ secrets.OSSRH_PASSWORD }}
            -Ptag_version=${{ steps.version.outputs.tag_version }}
        run: ./gradlew ${GRADLE_VARS} publish